"""borona: tipo de venta y conversiones

Revision ID: 09f4d3e5e66b
Revises: bceff25b8b0d
Create Date: 2026-07-14 17:14:34.871844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '09f4d3e5e66b'
down_revision: Union[str, None] = 'bceff25b8b0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversiones_borona',
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('kilos', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('observaciones', sa.String(length=300), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversiones_borona_empresa_id'), 'conversiones_borona', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_conversiones_borona_estado'), 'conversiones_borona', ['estado'], unique=False)
    op.create_index(op.f('ix_conversiones_borona_fecha'), 'conversiones_borona', ['fecha'], unique=False)
    op.add_column('ventas_queso', sa.Column('tipo', sa.String(length=20), server_default='queso', nullable=False))
    op.create_index(op.f('ix_ventas_queso_tipo'), 'ventas_queso', ['tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ventas_queso_tipo'), table_name='ventas_queso')
    op.drop_column('ventas_queso', 'tipo')
    op.drop_index(op.f('ix_conversiones_borona_fecha'), table_name='conversiones_borona')
    op.drop_index(op.f('ix_conversiones_borona_estado'), table_name='conversiones_borona')
    op.drop_index(op.f('ix_conversiones_borona_empresa_id'), table_name='conversiones_borona')
    op.drop_table('conversiones_borona')
    # ### end Alembic commands ###
