"""esquema inicial

Revision ID: a3b2e63208bd
Revises: 
Create Date: 2026-07-10 17:04:34.222273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a3b2e63208bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditorias',
    sa.Column('empresa_id', sa.Uuid(), nullable=True),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('ip', sa.String(length=60), nullable=True),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('accion', sa.String(length=30), nullable=False),
    sa.Column('entidad', sa.String(length=80), nullable=False),
    sa.Column('entidad_id', sa.Uuid(), nullable=True),
    sa.Column('antes', sa.JSON(), nullable=True),
    sa.Column('despues', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditorias_accion'), 'auditorias', ['accion'], unique=False)
    op.create_index(op.f('ix_auditorias_empresa_id'), 'auditorias', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_auditorias_entidad_id'), 'auditorias', ['entidad_id'], unique=False)
    op.create_index(op.f('ix_auditorias_estado'), 'auditorias', ['estado'], unique=False)
    op.create_index(op.f('ix_auditorias_modulo'), 'auditorias', ['modulo'], unique=False)
    op.create_index(op.f('ix_auditorias_usuario_id'), 'auditorias', ['usuario_id'], unique=False)
    op.create_table('empresas',
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('nit', sa.String(length=30), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=100), server_default='Colombia', nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=True),
    sa.Column('logo_url', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nit')
    )
    op.create_index(op.f('ix_empresas_estado'), 'empresas', ['estado'], unique=False)
    op.create_table('login_audits',
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('username_intentado', sa.String(length=150), nullable=True),
    sa.Column('exito', sa.Boolean(), nullable=False),
    sa.Column('motivo', sa.String(length=200), nullable=True),
    sa.Column('ip', sa.String(length=60), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_audits_estado'), 'login_audits', ['estado'], unique=False)
    op.create_index(op.f('ix_login_audits_usuario_id'), 'login_audits', ['usuario_id'], unique=False)
    op.create_table('permisos',
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('accion', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('modulo', 'accion', name='uq_permiso_modulo_accion')
    )
    op.create_index(op.f('ix_permisos_estado'), 'permisos', ['estado'], unique=False)
    op.create_index(op.f('ix_permisos_modulo'), 'permisos', ['modulo'], unique=False)
    op.create_table('roles',
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('es_sistema', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_roles_estado'), 'roles', ['estado'], unique=False)
    op.create_table('categorias_gasto',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_gasto_empresa_id'), 'categorias_gasto', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_categorias_gasto_estado'), 'categorias_gasto', ['estado'], unique=False)
    op.create_table('clientes',
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('documento', sa.String(length=30), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_documento'), 'clientes', ['documento'], unique=False)
    op.create_index(op.f('ix_clientes_empresa_id'), 'clientes', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_clientes_estado'), 'clientes', ['estado'], unique=False)
    op.create_table('cuentas_bancarias',
    sa.Column('banco', sa.String(length=100), nullable=False),
    sa.Column('numero_cuenta', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('titular', sa.String(length=150), nullable=True),
    sa.Column('saldo_inicial', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuentas_bancarias_empresa_id'), 'cuentas_bancarias', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_cuentas_bancarias_estado'), 'cuentas_bancarias', ['estado'], unique=False)
    op.create_table('notificaciones',
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensaje', sa.String(length=500), nullable=False),
    sa.Column('referencia', sa.String(length=200), nullable=True),
    sa.Column('leida', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificaciones_empresa_id'), 'notificaciones', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_notificaciones_estado'), 'notificaciones', ['estado'], unique=False)
    op.create_index(op.f('ix_notificaciones_leida'), 'notificaciones', ['leida'], unique=False)
    op.create_index(op.f('ix_notificaciones_tipo'), 'notificaciones', ['tipo'], unique=False)
    op.create_index(op.f('ix_notificaciones_usuario_id'), 'notificaciones', ['usuario_id'], unique=False)
    op.create_table('rol_permisos',
    sa.Column('rol_id', sa.Uuid(), nullable=False),
    sa.Column('permiso_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id')
    )
    op.create_table('rutas',
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rutas_empresa_id'), 'rutas', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_rutas_estado'), 'rutas', ['estado'], unique=False)
    op.create_table('sucursales',
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('responsable', sa.String(length=150), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sucursales_empresa_id'), 'sucursales', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_sucursales_estado'), 'sucursales', ['estado'], unique=False)
    op.create_table('tipos_queso',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('precio_referencia', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_queso_empresa_id'), 'tipos_queso', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_tipos_queso_estado'), 'tipos_queso', ['estado'], unique=False)
    op.create_table('cajas_diarias',
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('sucursal_id', sa.Uuid(), nullable=True),
    sa.Column('saldo_inicial', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_ingresos', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_egresos', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('saldo_final', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('efectivo_contado', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('diferencia', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'fecha', 'sucursal_id', name='uq_caja_fecha_sucursal')
    )
    op.create_index(op.f('ix_cajas_diarias_empresa_id'), 'cajas_diarias', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_cajas_diarias_estado'), 'cajas_diarias', ['estado'], unique=False)
    op.create_index(op.f('ix_cajas_diarias_fecha'), 'cajas_diarias', ['fecha'], unique=False)
    op.create_table('gastos',
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('categoria_id', sa.Uuid(), nullable=False),
    sa.Column('concepto', sa.String(length=200), nullable=False),
    sa.Column('proveedor', sa.String(length=150), nullable=True),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('numero_factura', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('adjunto_url', sa.String(length=300), nullable=True),
    sa.Column('sucursal_id', sa.Uuid(), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_gasto.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gastos_categoria_id'), 'gastos', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_gastos_empresa_id'), 'gastos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_gastos_estado'), 'gastos', ['estado'], unique=False)
    op.create_index(op.f('ix_gastos_fecha'), 'gastos', ['fecha'], unique=False)
    op.create_table('movimientos_bancarios',
    sa.Column('cuenta_id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('concepto', sa.String(length=200), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('conciliado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('fecha_conciliacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas_bancarias.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_bancarios_cuenta_id'), 'movimientos_bancarios', ['cuenta_id'], unique=False)
    op.create_index(op.f('ix_movimientos_bancarios_empresa_id'), 'movimientos_bancarios', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_movimientos_bancarios_estado'), 'movimientos_bancarios', ['estado'], unique=False)
    op.create_index(op.f('ix_movimientos_bancarios_fecha'), 'movimientos_bancarios', ['fecha'], unique=False)
    op.create_table('producciones',
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo_queso_id', sa.Uuid(), nullable=False),
    sa.Column('sucursal_id', sa.Uuid(), nullable=True),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('peso_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('litros_usados', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rendimiento', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('merma', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.ForeignKeyConstraint(['tipo_queso_id'], ['tipos_queso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producciones_empresa_id'), 'producciones', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_producciones_estado'), 'producciones', ['estado'], unique=False)
    op.create_index(op.f('ix_producciones_fecha'), 'producciones', ['fecha'], unique=False)
    op.create_table('productos',
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('categoria', sa.String(length=30), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('stock_minimo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tipo_queso_id', sa.Uuid(), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['tipo_queso_id'], ['tipos_queso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_categoria'), 'productos', ['categoria'], unique=False)
    op.create_index(op.f('ix_productos_empresa_id'), 'productos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_productos_estado'), 'productos', ['estado'], unique=False)
    op.create_table('proveedores',
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('documento', sa.String(length=30), nullable=True),
    sa.Column('vereda', sa.String(length=100), nullable=True),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('precio_litro', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ruta_id', sa.Uuid(), nullable=True),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['ruta_id'], ['rutas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proveedores_documento'), 'proveedores', ['documento'], unique=False)
    op.create_index(op.f('ix_proveedores_empresa_id'), 'proveedores', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_proveedores_estado'), 'proveedores', ['estado'], unique=False)
    op.create_table('transportadores',
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('documento', sa.String(length=30), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('ruta_id', sa.Uuid(), nullable=True),
    sa.Column('valor_transporte', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['ruta_id'], ['rutas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transportadores_documento'), 'transportadores', ['documento'], unique=False)
    op.create_index(op.f('ix_transportadores_empresa_id'), 'transportadores', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_transportadores_estado'), 'transportadores', ['estado'], unique=False)
    op.create_table('usuarios',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('documento', sa.String(length=30), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('foto_url', sa.String(length=300), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=True),
    sa.Column('sucursal_id', sa.Uuid(), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('intentos_fallidos', sa.Integer(), server_default='0', nullable=False),
    sa.Column('bloqueado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_usuarios_documento'), 'usuarios', ['documento'], unique=False)
    op.create_index(op.f('ix_usuarios_empresa_id'), 'usuarios', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_usuarios_estado'), 'usuarios', ['estado'], unique=False)
    op.create_table('ventas',
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('pagado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'numero', name='uq_venta_numero')
    )
    op.create_index(op.f('ix_ventas_cliente_id'), 'ventas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_ventas_empresa_id'), 'ventas', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_ventas_estado'), 'ventas', ['estado'], unique=False)
    op.create_index(op.f('ix_ventas_fecha'), 'ventas', ['fecha'], unique=False)
    op.create_table('liquidaciones',
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('proveedor_id', sa.Uuid(), nullable=True),
    sa.Column('transportador_id', sa.Uuid(), nullable=True),
    sa.Column('periodo_inicio', sa.Date(), nullable=False),
    sa.Column('periodo_fin', sa.Date(), nullable=False),
    sa.Column('total_litros', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('precio_promedio', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_bruto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('bonificaciones', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('descuentos', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valor_transporte', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('anticipos', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['transportador_id'], ['transportadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_liquidacion_periodo', 'liquidaciones', ['empresa_id', 'periodo_inicio', 'periodo_fin'], unique=False)
    op.create_index(op.f('ix_liquidaciones_empresa_id'), 'liquidaciones', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_liquidaciones_estado'), 'liquidaciones', ['estado'], unique=False)
    op.create_index(op.f('ix_liquidaciones_proveedor_id'), 'liquidaciones', ['proveedor_id'], unique=False)
    op.create_index(op.f('ix_liquidaciones_transportador_id'), 'liquidaciones', ['transportador_id'], unique=False)
    op.create_table('movimientos_caja',
    sa.Column('caja_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('concepto', sa.String(length=200), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['caja_id'], ['cajas_diarias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_caja_caja_id'), 'movimientos_caja', ['caja_id'], unique=False)
    op.create_index(op.f('ix_movimientos_caja_empresa_id'), 'movimientos_caja', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_movimientos_caja_estado'), 'movimientos_caja', ['estado'], unique=False)
    op.create_table('movimientos_inventario',
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('sucursal_id', sa.Uuid(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('referencia', sa.String(length=200), nullable=True),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_inventario_empresa_id'), 'movimientos_inventario', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_movimientos_inventario_estado'), 'movimientos_inventario', ['estado'], unique=False)
    op.create_index(op.f('ix_movimientos_inventario_fecha'), 'movimientos_inventario', ['fecha'], unique=False)
    op.create_index(op.f('ix_movimientos_inventario_producto_id'), 'movimientos_inventario', ['producto_id'], unique=False)
    op.create_table('pagos',
    sa.Column('venta_id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('metodo', sa.String(length=30), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.String(length=300), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_empresa_id'), 'pagos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_pagos_estado'), 'pagos', ['estado'], unique=False)
    op.create_index(op.f('ix_pagos_venta_id'), 'pagos', ['venta_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_index(op.f('ix_password_reset_tokens_estado'), 'password_reset_tokens', ['estado'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_usuario_id'), 'password_reset_tokens', ['usuario_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_index(op.f('ix_refresh_tokens_estado'), 'refresh_tokens', ['estado'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_usuario_id'), 'refresh_tokens', ['usuario_id'], unique=False)
    op.create_table('usuario_roles',
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('rol_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_id')
    )
    op.create_table('venta_detalles',
    sa.Column('venta_id', sa.Uuid(), nullable=False),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venta_detalles_estado'), 'venta_detalles', ['estado'], unique=False)
    op.create_index(op.f('ix_venta_detalles_venta_id'), 'venta_detalles', ['venta_id'], unique=False)
    op.create_table('anticipos',
    sa.Column('proveedor_id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('observaciones', sa.String(length=300), nullable=True),
    sa.Column('liquidacion_id', sa.Uuid(), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['liquidacion_id'], ['liquidaciones.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anticipos_empresa_id'), 'anticipos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_anticipos_estado'), 'anticipos', ['estado'], unique=False)
    op.create_index(op.f('ix_anticipos_liquidacion_id'), 'anticipos', ['liquidacion_id'], unique=False)
    op.create_index(op.f('ix_anticipos_proveedor_id'), 'anticipos', ['proveedor_id'], unique=False)
    op.create_table('liquidacion_detalles',
    sa.Column('liquidacion_id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('litros', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_litro', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['liquidacion_id'], ['liquidaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liquidacion_detalles_estado'), 'liquidacion_detalles', ['estado'], unique=False)
    op.create_index(op.f('ix_liquidacion_detalles_liquidacion_id'), 'liquidacion_detalles', ['liquidacion_id'], unique=False)
    op.create_table('recepciones_leche',
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('proveedor_id', sa.Uuid(), nullable=False),
    sa.Column('transportador_id', sa.Uuid(), nullable=True),
    sa.Column('ruta_id', sa.Uuid(), nullable=True),
    sa.Column('sucursal_id', sa.Uuid(), nullable=True),
    sa.Column('cantidad_litros', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_litro', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bonificaciones', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('descuentos', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('valor_bruto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valor_transporte', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valor_neto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('liquidacion_id', sa.Uuid(), nullable=True),
    sa.Column('liquidacion_transporte_id', sa.Uuid(), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['liquidacion_id'], ['liquidaciones.id'], ),
    sa.ForeignKeyConstraint(['liquidacion_transporte_id'], ['liquidaciones.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['ruta_id'], ['rutas.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.ForeignKeyConstraint(['transportador_id'], ['transportadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recepcion_fecha_proveedor', 'recepciones_leche', ['empresa_id', 'fecha', 'proveedor_id'], unique=False)
    op.create_index(op.f('ix_recepciones_leche_empresa_id'), 'recepciones_leche', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_recepciones_leche_estado'), 'recepciones_leche', ['estado'], unique=False)
    op.create_index(op.f('ix_recepciones_leche_fecha'), 'recepciones_leche', ['fecha'], unique=False)
    op.create_index(op.f('ix_recepciones_leche_liquidacion_id'), 'recepciones_leche', ['liquidacion_id'], unique=False)
    op.create_index(op.f('ix_recepciones_leche_liquidacion_transporte_id'), 'recepciones_leche', ['liquidacion_transporte_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recepciones_leche_liquidacion_transporte_id'), table_name='recepciones_leche')
    op.drop_index(op.f('ix_recepciones_leche_liquidacion_id'), table_name='recepciones_leche')
    op.drop_index(op.f('ix_recepciones_leche_fecha'), table_name='recepciones_leche')
    op.drop_index(op.f('ix_recepciones_leche_estado'), table_name='recepciones_leche')
    op.drop_index(op.f('ix_recepciones_leche_empresa_id'), table_name='recepciones_leche')
    op.drop_index('ix_recepcion_fecha_proveedor', table_name='recepciones_leche')
    op.drop_table('recepciones_leche')
    op.drop_index(op.f('ix_liquidacion_detalles_liquidacion_id'), table_name='liquidacion_detalles')
    op.drop_index(op.f('ix_liquidacion_detalles_estado'), table_name='liquidacion_detalles')
    op.drop_table('liquidacion_detalles')
    op.drop_index(op.f('ix_anticipos_proveedor_id'), table_name='anticipos')
    op.drop_index(op.f('ix_anticipos_liquidacion_id'), table_name='anticipos')
    op.drop_index(op.f('ix_anticipos_estado'), table_name='anticipos')
    op.drop_index(op.f('ix_anticipos_empresa_id'), table_name='anticipos')
    op.drop_table('anticipos')
    op.drop_index(op.f('ix_venta_detalles_venta_id'), table_name='venta_detalles')
    op.drop_index(op.f('ix_venta_detalles_estado'), table_name='venta_detalles')
    op.drop_table('venta_detalles')
    op.drop_table('usuario_roles')
    op.drop_index(op.f('ix_refresh_tokens_usuario_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_estado'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_usuario_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_estado'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_pagos_venta_id'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_estado'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_empresa_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_movimientos_inventario_producto_id'), table_name='movimientos_inventario')
    op.drop_index(op.f('ix_movimientos_inventario_fecha'), table_name='movimientos_inventario')
    op.drop_index(op.f('ix_movimientos_inventario_estado'), table_name='movimientos_inventario')
    op.drop_index(op.f('ix_movimientos_inventario_empresa_id'), table_name='movimientos_inventario')
    op.drop_table('movimientos_inventario')
    op.drop_index(op.f('ix_movimientos_caja_estado'), table_name='movimientos_caja')
    op.drop_index(op.f('ix_movimientos_caja_empresa_id'), table_name='movimientos_caja')
    op.drop_index(op.f('ix_movimientos_caja_caja_id'), table_name='movimientos_caja')
    op.drop_table('movimientos_caja')
    op.drop_index(op.f('ix_liquidaciones_transportador_id'), table_name='liquidaciones')
    op.drop_index(op.f('ix_liquidaciones_proveedor_id'), table_name='liquidaciones')
    op.drop_index(op.f('ix_liquidaciones_estado'), table_name='liquidaciones')
    op.drop_index(op.f('ix_liquidaciones_empresa_id'), table_name='liquidaciones')
    op.drop_index('ix_liquidacion_periodo', table_name='liquidaciones')
    op.drop_table('liquidaciones')
    op.drop_index(op.f('ix_ventas_fecha'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_estado'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_empresa_id'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_cliente_id'), table_name='ventas')
    op.drop_table('ventas')
    op.drop_index(op.f('ix_usuarios_estado'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_empresa_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_documento'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_transportadores_estado'), table_name='transportadores')
    op.drop_index(op.f('ix_transportadores_empresa_id'), table_name='transportadores')
    op.drop_index(op.f('ix_transportadores_documento'), table_name='transportadores')
    op.drop_table('transportadores')
    op.drop_index(op.f('ix_proveedores_estado'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_empresa_id'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_documento'), table_name='proveedores')
    op.drop_table('proveedores')
    op.drop_index(op.f('ix_productos_estado'), table_name='productos')
    op.drop_index(op.f('ix_productos_empresa_id'), table_name='productos')
    op.drop_index(op.f('ix_productos_categoria'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_producciones_fecha'), table_name='producciones')
    op.drop_index(op.f('ix_producciones_estado'), table_name='producciones')
    op.drop_index(op.f('ix_producciones_empresa_id'), table_name='producciones')
    op.drop_table('producciones')
    op.drop_index(op.f('ix_movimientos_bancarios_fecha'), table_name='movimientos_bancarios')
    op.drop_index(op.f('ix_movimientos_bancarios_estado'), table_name='movimientos_bancarios')
    op.drop_index(op.f('ix_movimientos_bancarios_empresa_id'), table_name='movimientos_bancarios')
    op.drop_index(op.f('ix_movimientos_bancarios_cuenta_id'), table_name='movimientos_bancarios')
    op.drop_table('movimientos_bancarios')
    op.drop_index(op.f('ix_gastos_fecha'), table_name='gastos')
    op.drop_index(op.f('ix_gastos_estado'), table_name='gastos')
    op.drop_index(op.f('ix_gastos_empresa_id'), table_name='gastos')
    op.drop_index(op.f('ix_gastos_categoria_id'), table_name='gastos')
    op.drop_table('gastos')
    op.drop_index(op.f('ix_cajas_diarias_fecha'), table_name='cajas_diarias')
    op.drop_index(op.f('ix_cajas_diarias_estado'), table_name='cajas_diarias')
    op.drop_index(op.f('ix_cajas_diarias_empresa_id'), table_name='cajas_diarias')
    op.drop_table('cajas_diarias')
    op.drop_index(op.f('ix_tipos_queso_estado'), table_name='tipos_queso')
    op.drop_index(op.f('ix_tipos_queso_empresa_id'), table_name='tipos_queso')
    op.drop_table('tipos_queso')
    op.drop_index(op.f('ix_sucursales_estado'), table_name='sucursales')
    op.drop_index(op.f('ix_sucursales_empresa_id'), table_name='sucursales')
    op.drop_table('sucursales')
    op.drop_index(op.f('ix_rutas_estado'), table_name='rutas')
    op.drop_index(op.f('ix_rutas_empresa_id'), table_name='rutas')
    op.drop_table('rutas')
    op.drop_table('rol_permisos')
    op.drop_index(op.f('ix_notificaciones_usuario_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_tipo'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_leida'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_estado'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_empresa_id'), table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_index(op.f('ix_cuentas_bancarias_estado'), table_name='cuentas_bancarias')
    op.drop_index(op.f('ix_cuentas_bancarias_empresa_id'), table_name='cuentas_bancarias')
    op.drop_table('cuentas_bancarias')
    op.drop_index(op.f('ix_clientes_estado'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_empresa_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_documento'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_categorias_gasto_estado'), table_name='categorias_gasto')
    op.drop_index(op.f('ix_categorias_gasto_empresa_id'), table_name='categorias_gasto')
    op.drop_table('categorias_gasto')
    op.drop_index(op.f('ix_roles_estado'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permisos_modulo'), table_name='permisos')
    op.drop_index(op.f('ix_permisos_estado'), table_name='permisos')
    op.drop_table('permisos')
    op.drop_index(op.f('ix_login_audits_usuario_id'), table_name='login_audits')
    op.drop_index(op.f('ix_login_audits_estado'), table_name='login_audits')
    op.drop_table('login_audits')
    op.drop_index(op.f('ix_empresas_estado'), table_name='empresas')
    op.drop_table('empresas')
    op.drop_index(op.f('ix_auditorias_usuario_id'), table_name='auditorias')
    op.drop_index(op.f('ix_auditorias_modulo'), table_name='auditorias')
    op.drop_index(op.f('ix_auditorias_estado'), table_name='auditorias')
    op.drop_index(op.f('ix_auditorias_entidad_id'), table_name='auditorias')
    op.drop_index(op.f('ix_auditorias_empresa_id'), table_name='auditorias')
    op.drop_index(op.f('ix_auditorias_accion'), table_name='auditorias')
    op.drop_table('auditorias')
    # ### end Alembic commands ###
