"""empleados

Revision ID: b7d4f1a9c3e2
Revises: 09f4d3e5e66b
Create Date: 2026-07-15 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b7d4f1a9c3e2'
down_revision: Union[str, None] = '09f4d3e5e66b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empleados',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('documento', sa.String(length=30), nullable=True),
    sa.Column('cargo', sa.String(length=80), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('salario', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empleados_documento'), 'empleados', ['documento'], unique=False)
    op.create_index(op.f('ix_empleados_empresa_id'), 'empleados', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_empleados_estado'), 'empleados', ['estado'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_empleados_estado'), table_name='empleados')
    op.drop_index(op.f('ix_empleados_empresa_id'), table_name='empleados')
    op.drop_index(op.f('ix_empleados_documento'), table_name='empleados')
    op.drop_table('empleados')
    # ### end Alembic commands ###
