"""reventa de queso

Revision ID: bceff25b8b0d
Revises: a3b2e63208bd
Create Date: 2026-07-14 16:12:05.052120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bceff25b8b0d'
down_revision: Union[str, None] = 'a3b2e63208bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compras_queso',
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('productor', sa.String(length=150), nullable=False),
    sa.Column('kilos_brutos', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('merma_kilos', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('borona_kilos', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('kilos_netos', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_kilo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('abonado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compras_queso_empresa_id'), 'compras_queso', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_compras_queso_estado'), 'compras_queso', ['estado'], unique=False)
    op.create_index(op.f('ix_compras_queso_fecha'), 'compras_queso', ['fecha'], unique=False)
    op.create_table('ventas_queso',
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cliente', sa.String(length=150), nullable=False),
    sa.Column('kilos', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_kilo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('abonado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ventas_queso_empresa_id'), 'ventas_queso', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_ventas_queso_estado'), 'ventas_queso', ['estado'], unique=False)
    op.create_index(op.f('ix_ventas_queso_fecha'), 'ventas_queso', ['fecha'], unique=False)
    op.create_table('abonos_compra_queso',
    sa.Column('compra_id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('observaciones', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['compra_id'], ['compras_queso.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abonos_compra_queso_compra_id'), 'abonos_compra_queso', ['compra_id'], unique=False)
    op.create_index(op.f('ix_abonos_compra_queso_estado'), 'abonos_compra_queso', ['estado'], unique=False)
    op.create_table('abonos_venta_queso',
    sa.Column('venta_id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('observaciones', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas_queso.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abonos_venta_queso_estado'), 'abonos_venta_queso', ['estado'], unique=False)
    op.create_index(op.f('ix_abonos_venta_queso_venta_id'), 'abonos_venta_queso', ['venta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_abonos_venta_queso_venta_id'), table_name='abonos_venta_queso')
    op.drop_index(op.f('ix_abonos_venta_queso_estado'), table_name='abonos_venta_queso')
    op.drop_table('abonos_venta_queso')
    op.drop_index(op.f('ix_abonos_compra_queso_estado'), table_name='abonos_compra_queso')
    op.drop_index(op.f('ix_abonos_compra_queso_compra_id'), table_name='abonos_compra_queso')
    op.drop_table('abonos_compra_queso')
    op.drop_index(op.f('ix_ventas_queso_fecha'), table_name='ventas_queso')
    op.drop_index(op.f('ix_ventas_queso_estado'), table_name='ventas_queso')
    op.drop_index(op.f('ix_ventas_queso_empresa_id'), table_name='ventas_queso')
    op.drop_table('ventas_queso')
    op.drop_index(op.f('ix_compras_queso_fecha'), table_name='compras_queso')
    op.drop_index(op.f('ix_compras_queso_estado'), table_name='compras_queso')
    op.drop_index(op.f('ix_compras_queso_empresa_id'), table_name='compras_queso')
    op.drop_table('compras_queso')
    # ### end Alembic commands ###
